#! /bin/sh

echo "Install xcode"
open https://developer.apple.com/xcode/
xcode-select --install
echo "Installing Homebrew"
/usr/bin/ruby -e "$(curl -fsSL \
https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install bazel
brew install buildifier
brew install cppcheck
brew install clang
brew install clang-format

